### ISSUE TITLE
(v1.0) pkg> add GoogleCharts ERROR: Unsatisfiable requirements detected for package GoogleCharts [2f8fdf4e]:

### ISSUE THREAD

**Issue by programistawpf** [jverzani/GoogleCharts.jl#27]
> (v1.0) pkg> st
>     Status `C:\Users\progr\.julia\environments\v1.0\Project.toml`
>   [a93c6f00] DataFrames v0.17.1
>   [d71aba96] ReadStat v0.4.1
>   [1463e38c] StatFiles v0.8.0
>   [c17dfb99] WinRPM v0.4.2
> 
> (v1.0) pkg> up
>   Updating registry at `C:\Users\progr\.julia\registries\General`
>   Updating git-repo `https://github.com/JuliaRegistries/General.git`
>  Resolving package versions...
>   Updating `C:\Users\progr\.julia\environments\v1.0\Project.toml`
>  [no changes]
>   Updating `C:\Users\progr\.julia\environments\v1.0\Manifest.toml`
>  [no changes]
>
>
> (v1.0) pkg> add GoogleCharts
>  Resolving package versions...
> ERROR: Unsatisfiable requirements detected for package GoogleCharts [2f8fdf4e]:
>  GoogleCharts [2f8fdf4e] log:
>  ├─possible versions are: 0.0.1-0.0.7 or uninstalled
>  ├─restricted to versions * by an explicit requirement, leaving only versions 0.0.1-0.0.7
>  └─restricted by compatibility requirements with DataFrames [a93c6f00] to versions: uninstalled — no versions left
>    └─DataFrames [a93c6f00] log:
>      ├─possible versions are: [0.1.0, 0.2.0-0.2.5, 0.3.0-0.3.16, 0.4.0-0.4.3, 0.5.0-0.5.12, 0.6.0-0.6.11, 0.7.0-0.7.8, 0.8.0-0.8.5, 0.9.0-0.9.1, 0.10.0-0.10.1, 0.11.0-0.11.7, 0.12.0, 0.13.0-0.13.1, 0.14.0-0.14.1, 0.15.0-0.15.2, 0.16.0, 0.17.0-0.17.1] or uninstalled
>      └─restricted to versions 0.17.1 by an explicit requirement, leaving only versions 0.17.1
> 

On Julia 0.7 is the same
Paul

**Comment by jverzani** [comment]
This package should be considered long dead and not worth resuscitating.
